### ISSUE TITLE
Next steps for this extension?

### ISSUE THREAD

**Issue by polywock** [polywock/gpt-search#12]
ChatGPT will introduce search functionality soon. When that happens, I'll probably stop working on GPT Search. 

Let me know if you have thoughts on the matter.

**Comment by polywock** [comment]
Looks like Search is now here. I don't think I'll update this extension any longer.

**Comment by dylanleon93** [comment]
Ah I was just looking to see if something happened. I feel like your extension is still superior to it, so I don't see a reason to stop using yours and switch to it. Though I can understand that there might be less users looking for this functionality since they have some innate mediocre version built in. That said, just recently the topics on the left side of my window no longer appear when I have the extension enabled. I'm able to use the search function still but the topics only show up if i disable the extension. If you're able to adjust that or advise me on how I could fix it I'd appreciate it! Otherwise, thank you for having built this extension, it has been very helpful for me.

**Comment by polywock** [comment]
> That said, just recently the topics on the left side of my window no longer appear when I have the extension enabled.

Bug I noticed with the newest ChatGPT update. Uploaded a fix earlier today but it might take a few to approve. For now, opening ChatGPT through the GPTs page seems to work. https://chatgpt.com/gpts

**Comment by polywock** [comment]
@dylanleon93 Update with fix approved on the Chrome web store.

**Comment by dylanleon93** [comment]
Appreciate you!

**Comment by polywock** [comment]
Thanks a ton for the support!
